data_filesystems:
  galaxyData:
  - size: 1
    vol_id: !!python/unicode 'vol-5e3c4436'
services:
- service: SGE
- service: Postgres
- service: Galaxy
static_filesystems:
- filesystem: galaxyIndices
  size: 600
  snap_id: snap-e1c7d08b
- filesystem: galaxyTools
  size: 2
  snap_id: snap-ac293ac6
